export const AGA_FACTS = [
  "Aga śpiewała hymn przedszkola 'Pod Kasztanem' z większym zaangażowaniem niż niejeden hymn państwowy.",
  "Aga zna na pamięć piosenkę o śmieciarkach Remondis Sanitech — jedyna żywa nośniczka tego skarbu kultury.",
  "Aga nie lubiła piosenki 'Agnieszka już dawno tutaj nie mieszka', ale śpiewała ją regularnie.",
  "Aga grała na skrzypcach i umie śpiewać — talent muzyczny rozwinięty daleko przed epoką korporacyjną.",
  "Jako dziecko Aga grała w Simsów 2 i urządzała domy meblami z IKEI — zamiłowanie do estetyki od małego.",
  "W wieku 2 lat Aga nie pojechała do Disneylandu. Wyrwa w jej wspomnieniach trwa do dziś.",
  "Aga spała na plaży na Santorini, bo ktoś zapomniał zarezerwować nocleg.",
  "Aga podróżowała jako dziecko do Tunezji i Egiptu, gdy inne dzieci znały te miejsca tylko z map.",
  "Z wycieczek szkolnych wracała z najwyżej 50 groszami — wszystko wydała na pamiątki dla rodziny.",
  "Aga tańczyła taniec ludowy — sport istniał w jej życiu, zanim oficjalnie przyznała, że istnieje.",
  "Aga kończyła każdy rok szkolny z czerwonym paskiem — świadectwo z paskiem to był jej standard.",
  "Aga dostała się do gimnazjum Da Vinci dzięki stypendium. Catering zamiast stołówki zmienił jej życie.",
  "Aga chodziła do słynnej poznańskiej Ósemki. Naturalny krok dla kogoś kto zbierał pasy od zawsze.",
  "Aga uciekła z obozu konnego. Szczegóły ewakuacji owiane są tajemnicą, skuteczność — nie.",
  "Aga boi się wszystkich zwierząt: dużych, małych, futrzastych i tych, które 'przecież nic nie zrobią'.",
  "Aga pojechała na obóz konny, mimo lęku przed zwierzętami. Wróciła szybciej niż planowano.",
  "Aga zjadła kawałek tortu z urodzinowego wypieku siostry Kasi jeszcze przed zdmuchnięciem świeczek.",
  "Aga studiowała pod presją sukcesu — kiedy inni liczyli opłacalność obecności na zajęciach.",
  "Staż w USA sfinansował Adze początki wielkiej miłości. Ameryka zrobiła swoje.",
  "Aga pracuje w świecie analizy danych i walki z nadużyciami — od Simsów do data science.",
  "Alicante jest dla Agi ważne podwójnie. Redakcja jest dyskretna, ale wie co wie.",
  "Aga mieszkała na Piątkowie, Morasku i w centrum Poznania — dokumentacja przeprowadzkowa obszerna.",
  "Aga prowadziła śledztwo dotyczące najlepszych lodów w Poznaniu. Ranking istnieje.",
  "Aga podróżowała do Japonii, Tajlandii, Nowego Jorku i USA — mapa punktów Marriott imponująca.",
  "Aga była na koncertach: Trójki, Kwiatu Jabłoni, Adele. Gustu jej nie brakuje.",
  "Zaręczyny Agi odbyły się na Etnie. Wulkan jako tło — nie każdy może to powiedzieć.",
  "Aga wzięła ślub w Separowie. Baby Sven — pluszak — był obecny i pozostał na dobre.",
  "Maja jest całym światem Agi. Na chwilę, spokojnie — ale jaki to był świat.",
  "Aga oglądała bajki po niemiecku w Niemczech, prosząc rodzinę o ciszę. Fabuła była ważniejsza niż język.",
  "Aga zbiera punkty Marriott z takim samym zapałem, z jakim jako dziecko zbierała czerwone paski.",
];
